
using System.Reflection;
using System;
using Assets._Project.Scripts.SaveAndLoad.SavableDelegates;
using Theblueway.SaveAndLoad.Samples.Samples.Scripts;
using Assets._Project.Scripts.Infrastructure;
using Assets._Project.Scripts.Infrastructure.AddressableInfra;
using Assets._Project.Scripts.SaveAndLoad;
using Assets._Project.Scripts.SaveAndLoad.SaveHandlerBases;
using Assets._Project.Scripts.UtilScripts;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Theblueway.SaveAndLoad.Samples.Samples.Scripts
{
    public class MyGameManager:MonoBehaviour
    {
        public static MyGameManager Singleton { get; internal set;  }


        public HashSet<RandomId> _objectIdsWhenEnteredWorld;


        public int LoadedWorldSceneIndex { get; set; }


		public bool IsObjectLoading => SaveAndLoadManager.IsObjectLoading(this);


        private void Awake()
        {
			if (IsObjectLoading) return;


            if (Singleton != null && Singleton != this)
            {
                Debug.LogError("Multiple instances of MyGameManager detected. Destroying duplicate instance.");
                Destroy(gameObject);
                return;
            }

            Singleton = this;
            DontDestroyOnLoad(gameObject);
        }










        public void OnBootstrapCompleted() { StartCoroutine(OnBootstrapCompletedRoutine()); }

        public IEnumerator OnBootstrapCompletedRoutine()
        {
            yield return MySceneManager.Singleton.OnBootstrapCompletedRoutine();

        }


        public void StartNewWorld(int index)
        {
            LoadedWorldSceneIndex = index;
            StartCoroutine(StartNewWorldRoutine(index));
        }

        public IEnumerator StartNewWorldRoutine(int index)
        {
            BeforeEnterWorld();

            yield return MySceneManager.Singleton.StartNewWorldRoutine(index);

            AfterEnterWorld();
        }




        public void LoadSavedWorld(string filePath)
        {
            StartCoroutine(LoadSavedWorldRoutine(filePath));
        }

        public IEnumerator LoadSavedWorldRoutine(string filePath)
        {
            BeforeEnterWorld();

            yield return MySceneManager.Singleton.PrepareLoadSavedWorldRoutine();

            yield return SaveAndLoadManager.Singleton.LoadRoutine(filePath);

            yield return MySceneManager.Singleton.OnLoadSavedWorldCompletedRoutine();

            AfterEnterWorld();
        }


        public void BeforeEnterWorld()
        {
            _objectIdsWhenEnteredWorld = Infra.Singleton.GetAllObjectIds();
        }

        public void AfterEnterWorld()
        {
            AddressableDb.Singleton.RegisterUnityBuiltinResources();
        }



        public void ExitWorld(Scene scene)
        {

            var allObjectIdsNow = Infra.Singleton.GetAllObjectIds();

            var addedObjects = new HashSet<RandomId>(allObjectIdsNow.Except(_objectIdsWhenEnteredWorld));
            
            foreach(var id in addedObjects)
            {
                Infra.Singleton.Unregister(id);
                AssetIdMap.ObjectIdToAssetId.Remove(id);
            }

            MySceneManager.Singleton.ExitWorld(scene);
        }
    
//#region SaveAndLoad AutoGenerated

///// auto-generated for <see cref="MyGameManager"/>
//		[SaveHandler(903542230583164971, handledType: typeof(Theblueway.SaveAndLoad.Samples.Samples.Scripts.MyGameManager), generationMode: SaveHandlerGenerationMode.Manual)]
//		public class MyGameManagerSaveHandler : MonoSaveHandler<Theblueway.SaveAndLoad.Samples.Samples.Scripts.MyGameManager, MyGameManagerSaveData> 
//		{
//			public override void WriteSaveData()
//			{
//				base.WriteSaveData();
//				__saveData.LoadedWorldSceneIndex = __instance.LoadedWorldSceneIndex;
//			}

//			public override void LoadPhase1()
//			{
//				base.LoadPhase1();
//				__instance.LoadedWorldSceneIndex = __saveData.LoadedWorldSceneIndex;
//			}
//        }


//		[SaveData(903542230583164971)]
//		public class MyGameManagerSaveData : MonoSaveDataBase 
//		{
//			public System.Int32 LoadedWorldSceneIndex;
//		}

///// end of auto-generated for <see cref="MyGameManager"/>
//#endregion
}
}
