
using Assets._Project.Scripts.SaveAndLoad;
using Assets._Project.Scripts.SaveAndLoad.SaveHandlerBases;
using Theblueway.SaveAndLoad.Samples.Samples.Scripts;
using UnityEditor.Overlays;
using UnityEngine;

namespace Theblueway.SaveAndLoad.Samples.Scripts
{
    public class MyPlayerWorldState:MonoBehaviour
    {
        internal static MyPlayerWorldState Singleton { get; set; }


        public bool IsObjectLoading => SaveAndLoadManager.IsObjectLoading(this);


        private void Awake()
        {
            //if (IsObjectLoading) return;


            if (Singleton != null && Singleton != this)
            {
                Debug.LogError("Multiple instances of MyGameManager detected. Destroying duplicate instance.");
                Destroy(gameObject);
                return;
            }

            Singleton = this;
        }



        public static MyPlayerWorldState GetStateOf(Component component)
        {
            return Singleton;
        }


        public void ExitWorld()
        {
            MyGameManager.Singleton.ExitWorld(gameObject.scene);
        }



        #region SaveAndLoad AutoGenerated

        /// auto-generated for <see cref="MyGameManager"/>
        [SaveHandler(903542230583164971, handledType: typeof(MyPlayerWorldState), generationMode: SaveHandlerGenerationMode.Configured)]
        public class MyPlayerWorldStateSaveHandler : MonoSaveHandler<MyPlayerWorldState, MyPlayerWorldStateSaveData>
        {
            public override void WriteSaveData()
            {
                base.WriteSaveData();
            }

            public override void LoadPhase1()
            {
                base.LoadPhase1();
            }

            public override void _AssignInstance()
            {
                __instance = MyPlayerWorldState.Singleton;
            }
        }


        [SaveData(903542230583164971)]
        public class MyPlayerWorldStateSaveData : MonoSaveDataBase
        {
            public System.Int32 LoadedWorldSceneIndex;
        }

        /// end of auto-generated for <see cref="MyPlayerWorldState"/>
        #endregion
    }
}
